# Generated by Django 6.0.3 on 2026-09-10 22:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('necta_news', 'NECTA news'), ('reliefweb_job', 'ReliefWeb job')], max_length=30)),
                ('external_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'external_id'], name='ingestion_i_source_a72eff_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
