# Generated by Django 6.0.3 on 2026-08-18 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, max_length=2000)),
                ('audience', models.CharField(choices=[('connections', 'My Connections'), ('cohort', 'School / Cohort'), ('public', 'Public')], default='connections', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_assets.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', '-created_at'], name='posts_post_author__f8ea20_idx')],
            },
        ),
    ]
