# Generated by Django 6.0.3 on 2026-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=20),
        ),
    ]
