# Generated by Django 6.0.3 on 2026-09-29 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postcomment_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_repost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='reposted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='audience',
            field=models.CharField(choices=[('connections', 'My Connections'), ('cohort', 'My Cohort'), ('school', 'My School'), ('public', 'Public')], default='connections', max_length=20),
        ),
    ]
