# Generated by Django 6.0.3 on 2026-09-21 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_userrelationshipoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='message',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['receiver', 'status', '-created_at'], name='conn_receiver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['requester', 'status'], name='conn_requester_status_idx'),
        ),
    ]
