# Generated by Django 6.0.3 on 2026-03-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('school_type', models.CharField(choices=[('secondary', 'Secondary School'), ('primary', 'Primary School'), ('university', 'University')], default='secondary', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
