# Generated by Django 6.0.3 on 2026-07-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('secondary', 'Secondary School (O-Level)'), ('primary', 'Primary School'), ('high_school', 'High School (A-Level)'), ('university', 'University')], default='secondary', max_length=20),
        ),
    ]
