# Generated by Django 6.0.3 on 2026-04-06 21:08

import django.db.models.deletion
from django.db import migrations, models


def disable_fk_checks(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute("PRAGMA foreign_keys = OFF;")


def enable_fk_checks(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute("PRAGMA foreign_keys = ON;")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_current_location_user_high_school_and_more'),
        ('alumni', '0001_initial'),
    ]

    operations = [
        # Disable foreign key constraints temporarily (SQLite only; Postgres doesn't need this)
        migrations.RunPython(disable_fk_checks, enable_fk_checks),

        # Clear school fields
        migrations.RunSQL(
            "UPDATE accounts_user SET primary_school = NULL, secondary_school = NULL;",
            migrations.RunSQL.noop
        ),
        
        # Remove old fields
        migrations.RemoveField(
            model_name='user',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        
        # Convert primary_school to ForeignKey
        migrations.AlterField(
            model_name='user',
            name='primary_school',
            field=models.ForeignKey(blank=True, limit_choices_to={'school_type': 'primary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_alumni', to='alumni.school'),
        ),
        
        # Convert secondary_school to ForeignKey
        migrations.AlterField(
            model_name='user',
            name='secondary_school',
            field=models.ForeignKey(blank=True, limit_choices_to={'school_type': 'secondary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_alumni', to='alumni.school'),
        ),
        
        # Re-enable foreign key constraints (SQLite only)
        migrations.RunPython(enable_fk_checks, disable_fk_checks),
    ]
