# Generated by Django 6.0.3 on 2026-07-03 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_convert_schools_to_fk'),
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-employed'), ('business_owner', 'Business Owner')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tertiary_completion_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tertiary_school',
            field=models.ForeignKey(blank=True, limit_choices_to={'school_type': 'university'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tertiary_alumni', to='alumni.school'),
        ),
    ]
