# Generated by Django 6.0.3 on 2026-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_email_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], default='en', max_length=5),
        ),
    ]
