# Generated by Django 6.0.3 on 2026-09-23 06:45

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/', validators=[accounts.validators.validate_avatar_image]),
        ),
    ]
