"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default="False") == "True"


ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS", default="legacylink-app-qs7gl.ondigitalocean.app,localhost,127.0.0.1"
).split(",")
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS", default="https://legacylink-app-qs7gl.ondigitalocean.app"
).split(",")
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'storages',
    # Social login disabled due to compatibility with custom User model
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    
    # Our apps
    'accounts',
    'alumni',
    'connections',
    'feedback',
    'opportunities',
    'messaging',
    'media_assets',
]

SITE_ID = 1

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first!
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'  # Custom user model

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS", default="https://legacylink-app-qs7gl.ondigitalocean.app"
).split(",")

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# User-uploaded media (avatars, etc.) — Cloudflare R2 (S3-compatible), so
# files persist across deploys instead of vanishing when Render's web
# service disk resets (it's ephemeral; local filesystem storage silently
# lost every avatar on the last redeploy). Falls back to local filesystem
# storage when R2 isn't configured, so local dev works without R2 credentials.
if config('R2_ACCESS_KEY_ID', default=''):
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
    AWS_ACCESS_KEY_ID = config('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('R2_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = config('R2_ENDPOINT_URL')
    AWS_S3_CUSTOM_DOMAIN = config('R2_PUBLIC_DOMAIN')
    # Objects must be explicitly made public on upload — the bucket itself
    # doesn't grant public read by default (unlike the original R2 bucket),
    # so leaving this unset (None) uploaded files that returned 403 on their
    # public URL even though the upload itself succeeded.
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_ADDRESSING_STYLE = 'virtual'
    AWS_S3_FILE_OVERWRITE = False

# ---------------------------------------------------------------------------
# Media assets (Phase 1) — private pipeline for message/post attachments,
# separate from the public-read avatar storage above. Reuses the same
# R2/Spaces bucket + credentials (no duplicate secrets) but writes under its
# own private prefixes and talks to S3 directly via boto3 (not through
# django-storages), because the STORAGES default above is globally
# public-read/unsigned and shared with avatars — changing that global config
# to be private would break avatar serving. When no bucket credentials are
# configured (local dev), falls back to filesystem storage under a directory
# Django never serves publicly, with signed local URLs standing in for
# presigned S3 URLs — same fallback pattern already used for the default
# storage above, so local dev keeps working without cloud credentials.
MEDIA_ASSETS_S3_ENABLED = bool(config('R2_ACCESS_KEY_ID', default=''))
MEDIA_ASSETS_S3_ACCESS_KEY_ID = config('R2_ACCESS_KEY_ID', default='')
MEDIA_ASSETS_S3_SECRET_ACCESS_KEY = config('R2_SECRET_ACCESS_KEY', default='')
MEDIA_ASSETS_S3_BUCKET_NAME = config('R2_BUCKET_NAME', default='')
MEDIA_ASSETS_S3_ENDPOINT_URL = config('R2_ENDPOINT_URL', default='')
MEDIA_ASSETS_S3_REGION = config('MEDIA_ASSETS_S3_REGION', default='us-east-1')

MEDIA_ASSETS_LOCAL_ROOT = BASE_DIR / 'private_media'  # never added to MEDIA_ROOT/served publicly

MEDIA_ASSETS_QUARANTINE_PREFIX = 'private/quarantine/'
MEDIA_ASSETS_READY_PREFIX = 'private/ready/'
MEDIA_ASSETS_THUMBNAIL_PREFIX = 'private/thumbnails/'

MEDIA_ASSETS_UPLOAD_URL_TTL_SECONDS = config('MEDIA_UPLOAD_URL_TTL_SECONDS', default=600, cast=int)
MEDIA_ASSETS_SIGNED_URL_TTL_SECONDS = config('MEDIA_SIGNED_URL_TTL_SECONDS', default=300, cast=int)

MEDIA_ASSETS_IMAGE_MAX_BYTES = config('MEDIA_IMAGE_MAX_MB', default=10, cast=int) * 1024 * 1024
MEDIA_ASSETS_VIDEO_MAX_BYTES = config('MEDIA_VIDEO_MAX_MB', default=50, cast=int) * 1024 * 1024
MEDIA_ASSETS_DOCUMENT_MAX_BYTES = config('MEDIA_PDF_MAX_MB', default=10, cast=int) * 1024 * 1024
MEDIA_ASSETS_VIDEO_MAX_DURATION_SECONDS = config('MEDIA_VIDEO_MAX_DURATION_SECONDS', default=60, cast=int)
MEDIA_ASSETS_IMAGE_MAX_DIMENSION = config('MEDIA_IMAGE_MAX_DIMENSION', default=2048, cast=int)
# Guards against decompression bombs: reject images whose *decoded* pixel
# count would exceed this, checked before any resize/re-encode is attempted.
MEDIA_ASSETS_IMAGE_MAX_PIXELS = config('MEDIA_IMAGE_MAX_PIXELS', default=40_000_000, cast=int)

# How long an unattached (orphan) asset survives before the cleanup command
# purges it — also applies to stuck INITIALIZED uploads and terminal
# FAILED/REJECTED rows.
MEDIA_ASSETS_RETENTION_HOURS = config('MEDIA_ORPHAN_RETENTION_HOURS', default=72, cast=int)

# Master switch for the whole init-upload endpoint. Per-category switches
# below let ops disable just video or just documents (e.g. if ffprobe/clamd
# aren't provisioned on a given host yet) without disabling images too.
FEATURE_MEDIA_UPLOADS_ENABLED = config('FEATURE_MEDIA_UPLOADS_ENABLED', default='False') == 'True'
FEATURE_VIDEO_MEDIA_ENABLED = config('FEATURE_VIDEO_MEDIA_ENABLED', default='False') == 'True'
# Required by spec: a dedicated flag for document (PDF) media specifically,
# since PDFs are the only category needing AV scanning.
FEATURE_DOCUMENT_MEDIA_ENABLED = config('FEATURE_DOCUMENT_MEDIA_ENABLED', default='False') == 'True'

# ClamAV (clamd) — new infra, not currently provisioned anywhere in this
# project. Left blank, document uploads fail closed (see
# media_assets/scanning.py::NullScanner) rather than being marked safe.
MEDIA_ASSETS_CLAMD_HOST = config('CLAMD_HOST', default='')
MEDIA_ASSETS_CLAMD_PORT = config('CLAMD_PORT', default=3310, cast=int)
MEDIA_ASSETS_CLAMD_TIMEOUT_SECONDS = config('CLAMD_TIMEOUT_SECONDS', default=15, cast=int)

# ffprobe/ffmpeg — new infra, not currently provisioned anywhere in this
# project. Video uploads fail closed if the binaries aren't found (see
# media_assets/validation.py).
MEDIA_ASSETS_FFPROBE_PATH = config('FFPROBE_PATH', default='ffprobe')
MEDIA_ASSETS_FFMPEG_PATH = config('FFMPEG_PATH', default='ffmpeg')

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # Only return JSON, hide browsable API
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'messaging.context_processors.unread_message_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Read DATABASE_URL via decouple (checks OS env first, then .env) instead of
# dj_database_url.config(), which only reads the OS environment — a .env
# DATABASE_URL line was silently ignored before this.
DATABASES = {
    'default': dj_database_url.parse(
        config('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Authentication settings
AUTHENTICATION_BACKENDS = [
    'accounts.backends.PhoneOrEmailBackend',
]

LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'

# Email — used to notify the team when pilot users submit feedback (see
# feedback app). Gmail SMTP with an App Password. If EMAIL_HOST_USER isn't
# set, falls back to printing emails to the console instead of sending them,
# so local dev works without credentials.
if config('EMAIL_HOST_USER', default=''):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default='True') == 'True'
    EMAIL_HOST_USER = config('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
    DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
    EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@legacylinkafrica.local'

FEEDBACK_NOTIFY_EMAIL = config('FEEDBACK_NOTIFY_EMAIL', default='')

# Django-allauth settings
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'
