# Generated by Django 6.0.3 on 2026-07-13 08:41

from django.db import migrations
from django.utils import timezone


def backfill_last_read_at(apps, schema_editor):
    """0003 added ConversationMember.last_read_at as NULL-by-default,
    replacing the old per-message Message.read_at. Any membership left NULL
    reads as 'never read anything', which would make every pre-existing
    message in every conversation appear freshly unread the moment this
    deploys — a false unread-notification spike for every user with an
    existing thread. Stamp existing memberships as read-through-now so only
    genuinely new messages count as unread going forward. (No-op on a fresh
    database with no existing conversations, e.g. production before this
    feature has ever been used.)"""
    ConversationMember = apps.get_model('messaging', 'ConversationMember')
    ConversationMember.objects.filter(last_read_at__isnull=True).update(last_read_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_remove_message_read_at_conversation_direct_key_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_last_read_at, migrations.RunPython.noop),
    ]
