# Generated by Django 6.0.3 on 2026-08-03 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('sanitized_filename', models.CharField(max_length=255)),
                ('declared_mime_type', models.CharField(blank=True, max_length=100)),
                ('detected_mime_type', models.CharField(blank=True, max_length=100)),
                ('declared_size_bytes', models.PositiveBigIntegerField()),
                ('original_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('processed_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('quarantine_storage_key', models.CharField(max_length=512, unique=True)),
                ('storage_key', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('thumbnail_storage_key', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('uploaded', 'Uploaded'), ('validating', 'Validating'), ('scanning', 'Scanning'), ('processing', 'Processing'), ('ready', 'Ready'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='initialized', max_length=20)),
                ('scan_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error')], default='not_required', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('moderation_hold', models.BooleanField(default=False)),
                ('moderation_note', models.TextField(blank=True)),
                ('is_attached', models.BooleanField(default=False)),
                ('upload_url_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='media_asset_owner_i_9e2e52_idx'), models.Index(fields=['status'], name='media_asset_status_9ea2f2_idx'), models.Index(fields=['purge_at'], name='media_asset_purge_a_ae2d56_idx')],
            },
        ),
    ]
