# Generated by Django 6.0.3 on 2026-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('connection_request', 'Connection request received'), ('connection_accepted', 'Connection request accepted'), ('post_approved', 'Post approved'), ('post_rejected', 'Post rejected'), ('post_liked', 'Post liked'), ('post_commented', 'Post commented'), ('new_message', 'New message')], max_length=30),
        ),
    ]
